name: Variables
run-name: I'm learning how to write variables for Github Actions!

on: 
    workflow_dispatch:

    pull_request:
        types: [opened, synchronize, reopened]
        branches: [ main ]
env: 
    STORED_NAME: ${{ vars.NAME }}
jobs:
    display-name:
        name: Display the name
        runs-on: ubuntu-latest
        steps:
            - name: Display the name
              run: echo "Hey, $STORED_NAME!"
